spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/abimaelrsergio/eazybytes-config.git"
        #native:
          #search-locations: "file:///D://config"
          #search-locations: "classpath:/config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
